// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: GeeCache/groupcachepb/groupcachepb.proto

package groupcachepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GroupRequest) Reset() {
	*x = GroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GeeCache_groupcachepb_groupcachepb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRequest) ProtoMessage() {}

func (x *GroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GeeCache_groupcachepb_groupcachepb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRequest.ProtoReflect.Descriptor instead.
func (*GroupRequest) Descriptor() ([]byte, []int) {
	return file_GeeCache_groupcachepb_groupcachepb_proto_rawDescGZIP(), []int{0}
}

func (x *GroupRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GroupRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View []byte `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
}

func (x *GroupReply) Reset() {
	*x = GroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GeeCache_groupcachepb_groupcachepb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupReply) ProtoMessage() {}

func (x *GroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_GeeCache_groupcachepb_groupcachepb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupReply.ProtoReflect.Descriptor instead.
func (*GroupReply) Descriptor() ([]byte, []int) {
	return file_GeeCache_groupcachepb_groupcachepb_proto_rawDescGZIP(), []int{1}
}

func (x *GroupReply) GetView() []byte {
	if x != nil {
		return x.View
	}
	return nil
}

var File_GeeCache_groupcachepb_groupcachepb_proto protoreflect.FileDescriptor

var file_GeeCache_groupcachepb_groupcachepb_proto_rawDesc = []byte{
	0x0a, 0x28, 0x47, 0x65, 0x65, 0x43, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x70, 0x62, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x0c, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x22, 0x20, 0x0a, 0x0a, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x76, 0x69, 0x65, 0x77, 0x32, 0x2f, 0x0a, 0x0a, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0d, 0x2e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x3b, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GeeCache_groupcachepb_groupcachepb_proto_rawDescOnce sync.Once
	file_GeeCache_groupcachepb_groupcachepb_proto_rawDescData = file_GeeCache_groupcachepb_groupcachepb_proto_rawDesc
)

func file_GeeCache_groupcachepb_groupcachepb_proto_rawDescGZIP() []byte {
	file_GeeCache_groupcachepb_groupcachepb_proto_rawDescOnce.Do(func() {
		file_GeeCache_groupcachepb_groupcachepb_proto_rawDescData = protoimpl.X.CompressGZIP(file_GeeCache_groupcachepb_groupcachepb_proto_rawDescData)
	})
	return file_GeeCache_groupcachepb_groupcachepb_proto_rawDescData
}

var file_GeeCache_groupcachepb_groupcachepb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GeeCache_groupcachepb_groupcachepb_proto_goTypes = []interface{}{
	(*GroupRequest)(nil), // 0: GroupRequest
	(*GroupReply)(nil),   // 1: GroupReply
}
var file_GeeCache_groupcachepb_groupcachepb_proto_depIdxs = []int32{
	0, // 0: GroupCache.Get:input_type -> GroupRequest
	1, // 1: GroupCache.Get:output_type -> GroupReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GeeCache_groupcachepb_groupcachepb_proto_init() }
func file_GeeCache_groupcachepb_groupcachepb_proto_init() {
	if File_GeeCache_groupcachepb_groupcachepb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_GeeCache_groupcachepb_groupcachepb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GeeCache_groupcachepb_groupcachepb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GeeCache_groupcachepb_groupcachepb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_GeeCache_groupcachepb_groupcachepb_proto_goTypes,
		DependencyIndexes: file_GeeCache_groupcachepb_groupcachepb_proto_depIdxs,
		MessageInfos:      file_GeeCache_groupcachepb_groupcachepb_proto_msgTypes,
	}.Build()
	File_GeeCache_groupcachepb_groupcachepb_proto = out.File
	file_GeeCache_groupcachepb_groupcachepb_proto_rawDesc = nil
	file_GeeCache_groupcachepb_groupcachepb_proto_goTypes = nil
	file_GeeCache_groupcachepb_groupcachepb_proto_depIdxs = nil
}
